name: demo
description: A CLI chat application using OpenRouter API
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  dio: ^5.4.0
  dotenv: ^4.2.0
  path: ^1.8.3
  ansicolor: ^2.0.3
  markdown: ^7.2.2
  equatable: ^2.0.7
  mime: ^2.0.0

dev_dependencies:
  lints: ^3.0.0

executables:
  chat: main 